#:kivy 1.11.1

<NorrisJokes>:
    lbl: joke

    BoxLayout:
        orientation: 'vertical'
        Button:
            background_normal: './chuck.jpg'
            # text: 'Generate Chuck Norris Joke'
            # font_size: '25'
            on_press: root.get_joke()

        Label:
            id: joke
            font_size: '25'
            text_size: cm(6), cm(4)
            size: self.texture_size
